export default `Roadmap to Becoming a Top Crypto Data Analyst - YouTube
https://www.youtube.com/watch?v=QdcQQKpTBZs

Transcript:
(00:00) what's up everyone Andrew here I'm going to teach you how to go from zero to one as a crypto data analyst so I've put together a short road map here where every single node is a key set of skills that you need to learn to really build up your crypto data portfolio learn to navigate the ecosystem and go out there
(00:18) and build reputation or get hired earn money trade whatever you want and so you can see here that I've broken things down into to modules so if you click into this you'll see that each node has some sort of description and some links I've tiered things into three levels level one level two level three level
(00:41) four you should not feel like you have to complete every level to move on to the next one some of these l3s or even l2s take a lot of time to work your way up to um it's just there so they that there's more for you to learn so every single section here they have again some explanation and links explaining you the key Concepts and then
(01:04) there will always be you should at the bottom right so this is meant to serve as a guideline here are the things you need to learn here's what you should be able to do for transactions traces and events learn what they are explore them the end of the day you should be able to go to Ether scan and be able to point
(01:21) out that's the function call that's the event those are the traces right obviously this get gets more complex with some of these other ones like ecosystem overviews these are complex dashboards and your goal is more of building an intuition which is uh learning like for any blockchain what metrics would you use maybe to compare
(01:41) them and that's going to be a theme kind of as you go through all of these that for example learning how raw data works that's just going through a bunch of documentation and learning how data is structured but by L3 it's really building an intuition of okay if I go to a dashboard what could they or could I build next
(02:01) that would make it better it's an intuition kind of same thing for all of these sections here so really comes in I think five or six different sections introduction to crypto if you know nothing about it easiest way to learn is just by using crypto you will need to learn some of the basics of blockchains
(02:18) I recommend getting up to L2 here before moving on exploration tools there are tons of data tools out there I've linked a guide for you to learn about what tools there are in crypto and you're just going to have to learn how to explore Trends addresses and transactions if you can't do those three and you try jumping straight into
(02:40) querying you're going to have a bad time I highly recommend that you don't do that cool querying obviously gets more complex there's a bunch of resources in here for you to go deeper and learn to build what you want to build obviously query comes with three other sub skill sets one of the harder ones is technical
(03:00) languages you can use SQL you could use python or r or you could use JavaScript um or typescript to build the analytics that you need for whatever your use case is I would pick one and roll with it sql's probably the easiest one don't try and learn all three before going deeper again this isn't a checklist you should
(03:22) learn what you need to and go build something and come back to this road map when you're like okay I feel comfortable what's next navigating protocols this is the one this takes a long time to build the intuition for uh if you just get comfortable with L1 and L2 on any protocol you're in good shape L3 and L4
(03:40) that probably took me a year to build good intuition for building in public this is an important one if all you do is query and create dashboards or reports or whatnot and you're not sharing it with people or like really trying to answer questions that you see from Key leaders on online you're losing
(03:58) most of the value right so you should learn how to G engage online what are the communities you can engage with you should learn that finding bounties and work is relationship building it's not just oh you can do the query so you get the work uh you have to go and basically answer questions online and engage with
(04:17) people in a meaningful way to build the relationships to then get the bounties ultimately you want to work your way up to high value contributions that's how you get really recognized IED in the space and by that point once you're recognized you can really do whatever you want there are a couple knowledge
(04:33) domains that you should learn so I've listed Seven main ones here you'll see that they're sparse I am still adding to this these will have their own subsections in the future but my suggestion is if you learn two or three of these domains you'll be pretty comfortable analyzing almost any protocol there's no way you get away
(04:53) with just analyzing one of them because of the composable nature of crypto every protocol or wallet or token touches multiple surfaces so it will be helpful for you to slowly build up the intuition and the knowledge around these different layers or domains over time and there are more domains than these
(05:12) there's Mev there's pers it goes deeper and deeper but these are the basic ones that are like you should be familiar with at least a little bit about how they work go check it out link is in the description have fun learning if you have questions or if you get lost you can go and DM me I'm happy to help out
(05:29) or if you have a resource that you want to contribute you can also DM me I'll add it in here and happy learning and good luck becoming a great crypto data analyst`;